# Header
menu:
  Home: /
  Archives: /archives
  Programing: /categories/programing
  Photography: /categories/photography
  Thoughts: /categories/thoughts

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /css/images/camera.png
twitter:
google_plus:
fb_admins:
fb_app_id:
